### ISSUE TITLE
Add compatibility with TerraFirmaCraft

### ISSUE THREAD

**Issue by witheredwojak** [caeruleusDraconis/world-preview#17]
When I try to use this mod with TerraFirmaCraft (version 3.1.2-beta), it shows me this error: 
![зображення](https://github.com/caeruleusDraconis/world-preview/assets/66310741/b4483433-ac60-4f5f-bf3f-3e66e6fddab4)

**Comment by caeruleusDraconis** [comment]
I am unable to reproduce this (TFC `3.1.2-beta`, Patchouli `1.20.1-83-FORGE`, World Preview `1.1.3`, Forge `47.2.17`). What versions are you using? Could you please attach the full Minecraft logs?

**Comment by caeruleusDraconis** [comment]
Additionally, the Y intersections view will always be a blank screen with TFC, because the the `TFCChunkGenerator` has a dummy implementation for the `getBaseColumn` method:

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/v3.1.2-beta/src/main/java/net/dries007/tfc/world/TFCChunkGenerator.java#L643-L646

**Comment by caeruleusDraconis** [comment]
Closing because of a lack of response.
