### ISSUE TITLE
Compatibility: Time & Wind (Fabric)

### ISSUE THREAD

**Issue by SurealSulwyn** [caeruleusDraconis/world-preview#19]
Minecraft: 1.20.1
Fabric Loader: 0.15.2

Fabric API: 0.91.0+1.20.1
World Preview: 1.1.4
Time & Wind (Fabric): 1.4.7+1.20 (works with 1.20-1.20.1)

I just added World Preview to my mod list; however, I was initially unable to get World Preview to load. I kept getting the "World Preview setup failed!" message, citing a compatibility issue. 

Through the process of elimination, I determined that this only occurs when Time & Wind is loaded alongside World Preview (also Fabric API which is required by both mods). No problems with any of the other 70+ mods in my mod list. 

https://www.curseforge.com/minecraft/mc-mods/time-wind

Not sure what about a mod that changes the length of a Minecraft day could cause World Preview to fail, but there you go.

**Comment by caeruleusDraconis** [comment]
> Not sure what about a mod that changes the length of a Minecraft day could cause World Preview to fail, but there you go.

World preview works by "starting" a fake Minecraft server without *aktually* executing any game logic. This allows us to manually generate biome / partial chunk data in parallel. Because of this, we also have to *manually* trigger the common hooks for other mods that interfere with world generation (otherwise we could only support vanilla world-gen). The [time-and-wind mod happens to also execute logic on such a trigger](https://github.com/CmdrJane/time-and-wind/blob/1.20/src/main/java/ru/aiefu/timeandwindct/mixin/ServerWorldMixins.java#L69-L83). However, it fails because we have likely missed a setup trigger that this mod relies on.

**Comment by caeruleusDraconis** [comment]
In this case, this isn't something that can be realistically worked around in World Preview. See my upstream PR: https://github.com/CmdrJane/time-and-wind/pull/26

In the meantime you can use my build of [time-and-wind-ct-1.4.7+1.20.zip](https://github.com/caeruleusDraconis/world-preview/files/13696049/time-and-wind-ct-1.4.7%2B1.20.zip) until there is an official release with the fix.

**Comment by SurealSulwyn** [comment]
Wow you work fast! *thumbs up* And thank you for the explanation of the cause of the compatibility issue. It was genuinely puzzling to me. Overall, what you and all other mod authors manage to make and do is pure magic!

**Comment by caeruleusDraconis** [comment]
Closing, because the upstream PR was merged.
