### ISSUE TITLE
Add compatibility with Xaero's Mini/WorldMap

### ISSUE THREAD

**Issue by craftish37** [caeruleusDraconis/world-preview#4]
While biomes may be difficult to implement as an overlay, structures or just right-clicking in the previewer to add a waypoint may be a good idea

Many other features may be addable in the future if you have any other idea ^^

**Comment by caeruleusDraconis** [comment]
This is unlikely to happen, since Xaero's Mini/WorldMap is closed source and (at least as far as I can tell) does not offer an API for adding waypoints / overlays. So, for this to happen we would need the support / permission of xaero96 and a public API to interface with the mod.

Basically something similar to https://github.com/TeamJM/journeymap-api but for Xaero's Mini/WorldMap.

That being said, adding features for specific mods is very low on our priority list.

Also, #3 must be first implemented before even considering supporting this.

**Comment by craftish37** [comment]
I do agree with your points, since it's closed source, developpment may be harder
However, I saw some other mods on modrinth implementing features to those mods and I believe there are ways to get there

https://github.com/plusls/xaero-map-addition
https://github.com/Abbie5/xaeroarrowfix
https://github.com/rfresh2/XaeroPlus/
https://github.com/NotRyken/XaeroZoomout

**Comment by caeruleusDraconis** [comment]
I had a quick look at these mods, and what they all have in common are that they are basically mods for Xaero's Min/WorldMap the same way that Xaero's Min/WorldMap is a mod for Minecraft.

They use the same mixin mechanism world-preview and other fabric mods use to modify Minecraft, to modify the Xaero's Min/WorldMap mod instead.

See [MinimapRendererMixin.java](https://github.com/Abbie5/xaeroarrowfix/blob/main/src/main/java/cc/abbie/xaeroarrowfix/mixin/MinimapRendererMixin.java) of https://github.com/Abbie5/xaeroarrowfix for instance.

So, *if* I would decide to mod Xaero's Min/WorldMap there would be no stability guarantees for new versions and I would possibly spend a considerable amount of time staying compatible with Xaero's Min/WorldMap **on top of** staying compatible with future versions of Minecraft...

This is not something that I would be willing to implement, let alone maintain.

So, unless xaero96 provides a public API this is not going to happen.
